Global g_Version := "3.0.1"
, g_AppName := "Auto-GUI"
, g_AppData := A_AppData . "\AmberSoft\Adventure"
, hAutoWnd
, Sci := []
, SciLexer := A_ScriptDir . (A_PtrSize == 8 ? "\SciLexer64.dll" : "\SciLexer32.dll")
, g_SciFontName
, g_SciFontSize
, IniFile
, IconLib := A_ScriptDir . "\Icons\Auto-GUI.icl"
, hChildWnd := 0
, Child := 1
, hSelWnd := 0
, hToolbar := 0
, hChildToolbar := 0
, TB_CHECKBUTTON := 0x402
, hFontDlg
, hCloneDlg
, hToolbarEditor := 0
, m := New MenuBar
, hMenuEditor := 0
, hAddMenuItemDlg := 0
, g
, g_X := 0
, g_Y := 0
, g_Control := 0
, g_OpenDir
, g_SaveDir
, Indent
, g_TabSize
, g_ShowGrid
, g_SnapToGrid
, g_GridSize
, g_WordWrap
, g_LineNumbers
, hLvToolbox
, hPropWnd := 0
, hCbxClassNN := 0
, hTabStyles
, g_oStyles
, g_PropX
, g_PropY
, hBitmapTile
, hCursorCross
, g_Cross := False
, CRLF := "`r`n"
, g_Signature := "; Generated by " . g_AppName . " " . g_Version . CRLF
, g_Resizers := []
, hResizer1
, hResizer2
, hResizer3
, hResizer4
, hResizer5
, hResizer6
, hResizer7
, hResizer8
, hReszdCtl
, g_ResizerSize := 6
, g_ResizerColor
, g_ResizerBrush
, g_Cursors := {}
, g_Adding := False
, g_NT6orLater := DllCall("Kernel32.dll\GetVersion") & 0xFF > 5
, g_TempFile := GetTempDir() . "\Temp.ahk"
, g_IconPath := "shell32.dll"
, g_PicturePath := A_MyDocuments
, g_GuiVis := False
, g_HighlightActiveLine
, g_IndentGuides
, g_Highlights
, g_HITMode
, g_HITLimit
, g_IndentWithSpaces
, g_InitialX
, g_InitialY
, g_InitialW
, g_InitialH
, g_ToolbarH := 30
, g_hStatusBar
, g_StatusBarH
, g_SplitterW := 4
, g_AskToSaveOnExit
, g_HelpFile
, g_ShowAllFonts
, g_FontList
, g_hHiddenEdit
, g_MenuFuncs
, g_MenuHandler
, g_CaretWidth
, g_CaretStyle
, g_CaretBlink
, g_Encodings := {"CP1252": "UTF-8 without BOM", "UTF-16": "UTF-16 LE", "UTF-8-RAW": "UTF-8 without BOM", "UTF-8": "UTF-8"}
, g_MaxEncodings := 3
, g_AhkPath64
, g_AhkPath32
, g_AhkPathEx
, g_MenuColor := 0xFAFAFA
, g_DefGUIFontName := "Segoe UI"
, g_DefGUIFontOpts := "s9"
, g_ShowToolbox := True
, g_ShowToolbar := True
, g_ShowStatusBar := True
